---

# среда запуска кода
env:
  node: true
  browser: true

extends:
  - 'airbnb-base'

rules:
  no-console: "off" # получить возможность использовать console
  import/extensions: "off" # получить возможность указывать при импорте файлы с расширением
  linebreak-style: ["error", "windows"] # linebreaks for windows
  wrap-iife: ["error", "inside"]
  no-var: "off"
  strict: "off"