const GET_SUMMARY_PANEL_DATA = 'SUMMARY/GET_PANEL_DATA';
const GET_DATA_LIST = 'TABULAR/GET_DATA_LIST';
const GET_RIGHTS_LIST = 'TABULAR/GET_RIGHTS_LIST';
const TABULAR_TYPE = 'TABULAR/TYPE';

export {
  GET_SUMMARY_PANEL_DATA,
  GET_DATA_LIST,
  GET_RIGHTS_LIST,
  TABULAR_TYPE,
};
